import os
import argparse
import sys

from google import genai
from google.genai import types
from dotenv import load_dotenv

from config import SYSTEM_PROMPT
from call_function import available_functions, call_function


load_dotenv()
api_key = os.environ.get("GEMINI_API_KEY")

if api_key is None:
    raise RuntimeError(
        "ERROR: Couldn't load api_key!. Please check the .env file."
    )

client = genai.Client(api_key=api_key)
parser = argparse.ArgumentParser(description='Chatbot')
parser.add_argument("user_prompt", type=str, help="User prompt")
parser.add_argument("--verbose", action="store_true",
                    help="Enable verbose output")
args = parser.parse_args()
messages = [types.Content(
    role="user", parts=[types.Part(text=args.user_prompt)])]

for iterations in range(20):
    if iterations == 20:
        print("Error: Maximum iterations reached!!")
        sys.exit(1)

    # Call the agent with all the function calls and user prompt
    answer = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=messages,
        config=types.GenerateContentConfig(
            tools=[available_functions],
            system_instruction=SYSTEM_PROMPT
        ),
    )

    # Check if the answer was generated by the agent
    if answer.usage_metadata is None:
        raise RuntimeError(
            "ERROR: There was an error when connecting to gemini api!. Please try again in some time."
        )

    if len(answer.candidates) != 0:
        for entry in answer.candidates:
            messages.append(entry.content)

    # Only print token usage if --verbose flag is set
    if args.verbose is True:
        print(f"User prompt: {args.user_prompt}")
        print(f"Prompt tokens: {answer.usage_metadata.prompt_token_count}")
        print(f"Response tokens: {
              answer.usage_metadata.candidates_token_count}")

    # create a list to store all the function results
    function_results = []
    if answer.function_calls is not None:
        for function_call in answer.function_calls:
            function_call_result = call_function(function_call)
            if len(function_call_result.parts) == 0:
                raise Exception("Error: Parts list was empty")
            if function_call_result.parts[0].function_response is None:
                raise Exception("Error: function_response was None")
            if function_call_result.parts[0].function_response.response is None:
                raise Exception(
                    "Error: function_response.response was None")
            function_results.append(function_call_result.parts[0])
            if args.verbose is True:
                print(
                    f"-> {function_call_result.parts[0].function_response.response}")
    else:
        print(f"Response: {answer.text}")
        break
    messages.append(types.Content(role="user", parts=function_results))
